services:
  playwright:
    image: ${COMPOSE_PROJECT_NAME}-playwright:${PROJECT_VERSION}
    platform: linux/amd64
    build:
      context: ./src/playwright
      args:
        PARENT_IMAGE: ${PLAYWRIGHT_IMAGE}
    environment:
      PAGE_WIDTH: ${PAGE_WIDTH}
      PAGE_HEIGHT: ${PAGE_HEIGHT}
      PAGE_WAIT_TIME: ${PAGE_WAIT_TIME}
    ports:
      - "3000:3000"
    networks:
      - default
  tools:
    image: ${COMPOSE_PROJECT_NAME}-tools:${PROJECT_VERSION}
    platform: linux/amd64
    build:
      context: ./src/tools
      args:
        PARENT_IMAGE: ${NODEJS_PARENT_IMAGE}
    environment:
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
      AZURE_STORAGE_ACCESS_KEY: ${AZURE_STORAGE_ACCESS_KEY}
      AZURE_STORAGE_CONTAINER: ${AZURE_STORAGE_CONTAINER}
      NEXT_SEARCH_DISCOVER: ${NEXT_SEARCH_DISCOVER}
      NEXT_SEARCH_ID: ${NEXT_SEARCH_ID}
      NEXT_ITEM_NUM: ${NEXT_ITEM_NUM}
      NEXT_PLAYWRIGHT_HOST_URI: ${NEXT_PLAYWRIGHT_HOST_URI}
    ports:
      - "3001:3000"
    networks:
      - default
