services:
  playwright:
    image: ${COMPOSE_PROJECT_NAME}-playwright:${PROJECT_VERSION}
    platform: linux/amd64
    build:
      context: ./src/playwright
      args:
        PARENT_IMAGE: ${PLAYWRIGHT_IMAGE}
    environment:
      PAGE_WIDTH: ${PAGE_WIDTH}
      PAGE_HEIGHT: ${PAGE_HEIGHT}
      PAGE_WAIT_TIME: ${PAGE_WAIT_TIME}
    ports:
      - "3000:3000"
    networks:
      - default
  thumbnail:
    image: ${COMPOSE_PROJECT_NAME}-thumbnail:${PROJECT_VERSION}
    platform: linux/amd64
    build:
      context: ./src/thumbnail
      args:
        PARENT_IMAGE: ${NODEJS_PARENT_IMAGE}
    environment:
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
      AZURE_STORAGE_ACCESS_KEY: ${AZURE_STORAGE_ACCESS_KEY}
      AZURE_STORAGE_CONTAINER: ${AZURE_STORAGE_CONTAINER}
      SEARCH_DISCOVER: ${SEARCH_DISCOVER}
    ports:
      - "5173:5173"
    networks:
      - default
